apiVersion: v1
kind: Service
metadata:
  annotations:
    logging: promtail
  name: bookstore-webapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: bookstore-webapp
