apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f apps.yaml -f infra.yaml -f monitoring.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bookstore-rabbitmq
  name: bookstore-rabbitmq
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    io.kompose.service: bookstore-rabbitmq
