apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-rabbitmq
  template:
    metadata:
      labels:
        app: bookstore-rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
          image: rabbitmq:3.12.11-management
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics check_port_connectivity
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 30
          name: bookstore-rabbitmq
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          resources:
            limits:
              memory: "524288e3"
      restartPolicy: Always
