apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: sinetztar/bookstore-catalog-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: DB_URL
              value: "jdbc:postgresql://catalog-db:15432/postgres"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: SWAGGER_API_GATEWAY
              value: "http://api-gateway:8989/catalog"
            - name: MANAGEMENT_TRACING_ENABLED
              value: "true"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tempo:9411"
          ports:
            - containerPort: 8081
