apiVersion: v1
kind: Service
metadata:
  annotations:
    logging: promtail
  name: notification-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: notification-service
