apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    logging: promtail
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      annotations:
        logging: promtail
      labels:
        app: order-service
    spec:
      containers:
        - env:
            - name: DB_PASSWORD
              value: postgres
            - name: DB_URL
              value: jdbc:postgresql://orders-db:25432/postgres
            - name: DB_USERNAME
              value: postgres
            - name: MANAGEMENT_TRACING_ENABLED
              value: "true"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://tempo:9411
            - name: OAUTH2_SERVER_URL
              value: http://keycloak:9191
            - name: ORDERS_CATALOG_SERVICE_URL
              value: http://api-gateway:8989/catalog
            - name: RABBITMQ_HOST
              value: bookstore-rabbitmq
            - name: RABBITMQ_PASSWORD
              value: guest
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SWAGGER_API_GATEWAY_URL
              value: http://api-gateway:8989/orders
          image: sinetztar/bookstore-order-service
          name: order-service
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            limits:
              memory: "734003200"
      restartPolicy: Always
