apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  ports:
    - name: "3200"
      port: 3200
      targetPort: 3200
    - name: "9411"
      port: 9411
      targetPort: 9411
  selector:
    app: tempo
